# Site settings
title: CyberBits
author: Chang Xu
email: xuxchang@hotmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  嗨！大家好，我是一名嵌入式软工，这里是我的个人博客，欢迎大家来访！
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 1
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  disqus:
    shortname: XxChang-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://github.com/XxChang
      icon: github
      color: purple

  # the animation speed of the scroll-in effect
  animation_speed: 50

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
